/**
 * GitHub Pull Request creator.
 * Uses GitHub REST API to create PRs and link them to issues.
 */

export interface CreatePROptions {
  /** PR title */
  title: string;
  /** PR body (markdown) */
  body: string;
  /** Source branch */
  head: string;
  /** Target branch (default: "main") */
  base?: string;
  /** Create as draft PR */
  draft?: boolean;
}

export interface PRResult {
  number: number;
  url: string;
  title: string;
  state: string;
}

export interface PRCreatorConfig {
  token: string;
  owner: string;
  repo: string;
  apiUrl?: string;
}

export class PRCreator {
  private readonly apiUrl: string;
  private readonly owner: string;
  private readonly repo: string;
  private readonly token: string;

  constructor(config: PRCreatorConfig) {
    this.apiUrl = (config.apiUrl ?? "https://api.github.com").replace(/\/$/, "");
    this.owner = config.owner;
    this.repo = config.repo;
    this.token = config.token;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const url = `${this.apiUrl}${path}`;
    const res = await fetch(url, {
      ...options,
      headers: {
        Authorization: `Bearer ${this.token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      throw new Error(`GitHub ${res.status} ${res.statusText}: ${body}`);
    }

    if (res.status === 204) return undefined as unknown as T;
    return res.json() as Promise<T>;
  }

  /** Create a pull request */
  async createPR(options: CreatePROptions): Promise<PRResult> {
    const data = await this.request<{
      number: number;
      html_url: string;
      title: string;
      state: string;
    }>(`/repos/${this.owner}/${this.repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({
        title: options.title,
        body: options.body,
        head: options.head,
        base: options.base ?? "main",
        draft: options.draft ?? false,
      }),
    });

    return {
      number: data.number,
      url: data.html_url,
      title: data.title,
      state: data.state,
    };
  }

  /** Generate a PR body from issue context and changes */
  static buildPRBody(opts: {
    issueNumber: number;
    summary: string;
    filesChanged: string[];
    testsRun: number;
    testsPassed: number;
  }): string {
    const { issueNumber, summary, filesChanged, testsRun, testsPassed } = opts;
    const fileList = filesChanged.map((f) => `- \`${f}\``).join("\n");
    const testStatus = testsPassed === testsRun ? "All passing" : `${testsPassed}/${testsRun} passing`;

    return [
      `Closes #${issueNumber}`,
      "",
      "## Summary",
      summary,
      "",
      "## Changes",
      fileList,
      "",
      `## Tests: ${testStatus}`,
      "",
      "---",
      "*This PR was automatically generated by TierZero.*",
    ].join("\n");
  }
}
