/**
 * GitHub Pull Request creator.
 * Uses GitHub REST API to create PRs and link them to issues.
 */

export interface CreatePROptions {
  /** PR title */
  title: string;
  /** PR body (markdown) */
  body: string;
  /** Source branch */
  head: string;
  /** Target branch (default: "main") */
  base?: string;
  /** Create as draft PR */
  draft?: boolean;
}

export interface PRResult {
  number: number;
  url: string;
  title: string;
  state: string;
}

export interface PRCreatorConfig {
  token: string;
  owner: string;
  repo: string;
  apiUrl?: string;
}

export class PRCreator {
  private readonly apiUrl: string;
  private readonly owner: string;
  private readonly repo: string;
  private readonly token: string;

  constructor(config: PRCreatorConfig) {
    this.apiUrl = (config.apiUrl ?? "https://api.github.com").replace(/\/$/, "");
    this.owner = config.owner;
    this.repo = config.repo;
    this.token = config.token;
  }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const url = `${this.apiUrl}${path}`;
    
    // Add simple retry logic for fetch failures
    let lastError: unknown;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        const res = await fetch(url, {
          ...options,
          headers: {
            Authorization: `Bearer ${this.token}`,
            Accept: "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            ...options.headers,
          },
        });

        if (!res.ok) {
          const body = await res.text().catch(() => "");
          throw new Error(`GitHub ${res.status} ${res.statusText}: ${body}`);
        }

        if (res.status === 204) return undefined as unknown as T;
        return (await res.json()) as T;
      } catch (err) {
        lastError = err;
        // If it's an HTTP error from GitHub, throw immediately (don't retry)
        if (err instanceof Error && err.message.startsWith("GitHub ")) {
          throw err;
        }
        // Otherwise it's likely a network/fetch error, wait and retry
        console.warn(`[PRCreator] Fetch failed on attempt ${attempt}/3: ${err instanceof Error ? err.message : String(err)}. Retrying in 2s...`);
        if (attempt < 3) await new Promise(resolve => setTimeout(resolve, 2000));
      }
    }
    throw lastError;
  }

  /** Create a pull request */
  async createPR(options: CreatePROptions): Promise<PRResult> {
    const data = await this.request<{
      number: number;
      html_url: string;
      title: string;
      state: string;
    }>(`/repos/${this.owner}/${this.repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({
        title: options.title,
        body: options.body,
        head: options.head,
        base: options.base ?? "main",
        draft: options.draft ?? false,
      }),
    });

    return {
      number: data.number,
      url: data.html_url,
      title: data.title,
      state: data.state,
    };
  }

  /** Merge a pull request */
  async mergePR(prNumber: number, method: "merge" | "squash" | "rebase" = "squash"): Promise<void> {
    await this.request(`/repos/${this.owner}/${this.repo}/pulls/${prNumber}/merge`, {
      method: "PUT",
      body: JSON.stringify({
        merge_method: method,
      }),
    });
  }

  /** Generate a PR body from issue context and changes */
  static buildPRBody(opts: {
    issueNumber: number;
    summary: string;
    filesChanged: string[];
    testsRun: number;
    testsPassed: number;
  }): string {
    const { issueNumber, summary, filesChanged, testsRun, testsPassed } = opts;
    const fileList = filesChanged.map((f) => `- \`${f}\``).join("\n");
    const testStatus = testsPassed === testsRun ? "All passing" : `${testsPassed}/${testsRun} passing`;

    return [
      `Closes #${issueNumber}`,
      "",
      "## Summary",
      summary,
      "",
      "## Changes",
      fileList,
      "",
      `## Tests: ${testStatus}`,
      "",
      "---",
      "*This PR was automatically generated by TierZero.*",
    ].join("\n");
  }
}
